name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Jorgeotero1998
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
